# Al-Ghazaly Auto Parts - ArgoCD Notifications Secret
# Store sensitive tokens here
# IMPORTANT: Replace placeholder values before applying!

apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  # Slack Bot Token (get from Slack App settings)
  slack-token: "xoxb-your-slack-bot-token"
  
  # GitHub Personal Access Token (for commit status updates)
  github-token: "ghp_your-github-token"
